# Generated by Django 5.1 on 2024-08-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('image', models.ImageField(upload_to='pradact_images/', verbose_name='изображение')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='публичность')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
            ],
            options={
                'verbose_name': 'новост',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
